apiVersion: v1
kind: List
items:
-
    apiVersion: v1
    kind: Deployment
    metadata:
        name: postgres
        labels:
            app: postgres
    spec:
        template:
          metadata:
              name: postgres
              app:
                  name: postgres
          spec:
              containers:
              - image: centos/postgresql-96-centos7
                name: postgres
                env:
                  - name: POSTGRESQL_USER
                    value: user
                  - name: POSTGRESQL_DATABASE
                    value: db
                  - name: POSTGRESQL_PASSWORD
                    value: pwd
                ports:
                - name: postgres
                  containerPort: 5432
                  volumeMounts:
                  - name: pg-storage
                    mountPath: /var/lib/postgresql/data
              volumes:
              - name: pg-storage
                persistentVolumeClaim:
                    claimName: pg-storage
-
    apiVersion: v1
    kind: Service
    metadata:
        name: postgres
        labels:
            app: postgres
            name: postgres
    spec:
        ports:
            - port: 5432
              targetPort: 5432
        selector:
            app: postgres
-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
        name: pg-storage
        labels:
          app: postgres
    spec:
        accessModes:
         - ReadWriteOnce
        resources:
            requests:
                storage: 1Gi