apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pg-storage
    labels:
      app: postgres
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi